---
title: "International Bench - ICT Sector"
output: 
      flexdashboard::flex_dashboard:
      orientation: rows
social: menu
source_code: "https://github.com/fabiorcampos/estudo_contencioso"
---

```{r, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
df = read.csv("./dataset/predict_2017_full.csv", header = TRUE, sep = ",", dec = ".", numerals = "no.loss")
int_cou = c("UK", "BR", "US", "KR", "CN")
euro_pps = "Millions of current euros PPS"
opr = "b) ICT sector (operational definition)"
sec = "A'=B'+C"
classfication = "261-264, 582, 61, 62, 631, 951"
countries = c("United Kingdom", "Brazil", "United States", "South Korea", "China")
berd_y = c(2008, 2011)
```

Gross R&D Expenditure (GERD)
=======================================================================

```{r, echo=FALSE, message=FALSE, warning=FALSE}
int_cou = c("UK", "BR", "US", "KR", "CN")
euro_pps = "Millions of current euros PPS"
euro_lab = "Millions of current euros"
opr = "b) ICT sector (operational definition)"
sec = "A'=B'+C"
classfication = "261-264, 582, 61, 62, 631, 951"
countries = c("United Kingdom", "Brazil", "United States", "South Korea", "China")
berd_y = c(2008, 2011)

gerd_df = filter(df, variablecode == "BERD", 
                  countrycode %in% c("BR", "UK", "US", "KR", "CN"), 
                  sectorcode == 'GERD', unit == euro_pps)

### International Benchmark
int_gerd = gerd_df
int_gerd = filter(int_gerd, year %in% c(2000:2013))
### uk tseries
uk_ts_gerd = filter(int_gerd, countrycode == "UK")
uk_ts_gerd = uk_ts_gerd$value
### us tseries
us_ts_gerd = filter(int_gerd, countrycode == "US")
us_ts_gerd = us_ts_gerd$value
### kr tseries
kr_ts_gerd = filter(int_gerd, countrycode == "KR")
kr_ts_gerd = kr_ts_gerd$value
### cn tseries
cn_ts_gerd = filter(int_gerd, countrycode == "CN")
cn_ts_gerd = cn_ts_gerd$value
```


Row
-----------------------------------------------------------------------

### Brazil GERD analysis 

```{r, echo=FALSE, message=FALSE, warning=FALSE}
br_gerd = filter(gerd_df, countrycode == "BR", !is.na(value))
ts_gerd = br_gerd$value
ts_year = br_gerd$year
plot_gebr = plot(ts_year, ts_gerd, type = 'l', col = "red",
                main = "Brazilian GERD Expenditures", 
                ylab = "Billions of current euros", xlab = "Years", 
                ylim = c(10000, 30000), xlim = c(2000, 2012),
                axes = FALSE)
axis(side = 1)
axis(side = 2, at= c(0, 10000, 15000, 20000, 25000, 30000), labels = c("0", "10", "15",
                                                                            "20", "25", "30"))
```

### International GERD analysis 

```{r, echo=FALSE, message=FALSE, warning=FALSE}
color = c("blue", "red", "black", "orange", "brown")
types = c('l', "b", "l", "o", "b")

plot_geint = plot(ts_year, ts_gerd, type = 'l', col = "red",
                  main = "International GERD Expenditures", ylab = euro_lab, xlab = "Years", ylim = c(10000, 400000), xlim = c(2000, 2013))
lines(ts_year, uk_ts_gerd, type = 'b', col = "blue")
lines(ts_year, us_ts_gerd, type = 'l', col = "black")
lines(ts_year, kr_ts_gerd, type = 'o', col = "orange")
lines(ts_year, cn_ts_gerd, type = 'b', col = "brown")
legend("topleft", countries, col = color, pch = c(1,1,1,1,1))
```

Row
-----------------------------------------------------------------------

###  International Benchmark

```{r, echo=FALSE, message=FALSE, warning=FALSE}
plot_geint = plot(ts_year, ts_gerd, type = 'l', col = "red",
                  main = "International GERD Expenditures", 
                  ylab = "Billions of current euros", xlab = "Years", 
                  ylim = c(0, 400000), xlim = c(2000, 2014),
                  axes = FALSE,
                  cex.axis = .7)
axis(side = 1)
axis(side = 2, at= c(0, 100000, 200000, 300000, 400000, 500000), labels = c("0", "100", "200","300", "400", "500"))
lines(ts_year, uk_ts_gerd, type = 'b', col = "blue")
lines(ts_year, us_ts_gerd, type = 'l', col = "black")
lines(ts_year, kr_ts_gerd, type = 'o', col = "orange")
lines(ts_year, cn_ts_gerd, type = 'b', col = "brown")
legend("topleft", countries, col = color, lwd = .8, cex = .8)
```

### International Benchmark

```{r, echo=FALSE, message=FALSE, warning=FALSE}
slices_gerd = c(30805, 29302, 337256, 50223, 246144)
pct = round(slices_gerd/sum(slices_gerd)*100)
countries_pie = paste(countries, pct) # add percents to labels
countries_pie = paste(countries_pie,"%",sep="") # ad % to labels
pie_gerd = pie(slices_gerd,labels = countries_pie, main="International GERD Expenditures - 2013") 
```

Gross Value Added (GVA)
=======================================================================

```{r, message=FALSE, warning=FALSE, include=FALSE}
ts_year_gva = c(1995:2014)

gva_df = filter(df, variablecode == "GVA", 
                 countrycode %in% c("BR", "UK", "US", "KR", "CN"), 
                 sectorcode == sec, unit == euro_pps, year %in% c(1995:2014))

gva_df = gva_df[,-c(1,2,5,6,7,8,9,10)]

### International Benchmark
int_gva = gva_df
### Brazil tseries
br_ts_gva = filter(int_gva, countrycode == "BR")
br_ts_gva = br_ts_gva$value
### uk tseries
uk_ts_gva = filter(int_gva, countrycode == "UK")
uk_ts_gva = uk_ts_gva$value
### us tseries
us_ts_gva = filter(int_gva, countrycode == "US")
us_ts_gva = us_ts_gva$value
### kr tseries
kr_ts_gva = filter(int_gva, countrycode == "KR")
kr_ts_gva = kr_ts_gva$value
### cn tseries
cn_ts_gva = filter(int_gva, countrycode == "CN")
cn_ts_gva = cn_ts_gva$value
```


Row
-----------------------------------------------------------------------

### International Benchmark 

```{r, echo=FALSE}
color = c("blue", "red", "black", "orange", "brown")
types = c('l', "b", "l", "o", "b")

plot_gvaint = plot(ts_year_gva, br_ts_gva, type = 'b', col = "red",
                  main = "International GVA", cex.axis=0.5, ylab = euro_lab, xlab = "Years", ylim = c(20000, 700000), xlim=c(1995, 2015))
lines(ts_year_gva, uk_ts_gva, type = 'l', col = "blue")
lines(ts_year_gva, us_ts_gva, type = 'l', col = "black")
lines(ts_year_gva, kr_ts_gva, type = 'o', col = "orange")
lines(ts_year_gva, cn_ts_gva, type = 'b', col = "brown")
legend("topleft", countries, col = color, pch = c(1,1,1,1,1), cex = .8)
```

### GVA Added

```{r, echo=FALSE, message=FALSE, warning=FALSE}
slices_gva = c(85746, 71243, 682883, 111103, 639963)
pct_gva <- round(slices_gva/sum(slices_gva)*100)
countries_pie_gva <- paste(countries, pct_gva) # add percents to labels
countries_pie_gva <- paste(countries_pie_gva,"%",sep="") # ad % to labels
pie_gva = pie(slices_gva,labels = countries_pie_gva, main="International GVA - 2014") 
```

Row
-----------------------------------------------------------------------

###  GVA Analysis

```{r, echo=FALSE}
boxp_gva_int = boxplot(uk_ts_gva, br_ts_gva, us_ts_gva, kr_ts_gva, cn_ts_gva, names = countries, main = "International GVA Comparision", ylab = euro_lab)
```

### Summary

```{r}
x1995 = c(uk_ts_gva[1], br_ts_gva[1], us_ts_gva[1], kr_ts_gva[1], cn_ts_gva[1]) 
x2014 = c(uk_ts_gva[20], br_ts_gva[20], us_ts_gva[20], kr_ts_gva[20], cn_ts_gva[20]) 
var = (x2014 - x1995) / x1995

gva_summary = data.frame(x1995, x2014, var, row.names = countries)
knitr::kable(gva_summary)
```

 R&D personnel (PERD)
=======================================================================

```{r, message=FALSE, warning=FALSE, include=FALSE}
int_cou = c("UK", "BR", "US", "KR", "CN")
euro_lab = "Millions of current euros"
sec_perd = "A=B+SER"
classfication = "261-264, 582, 61, 62, 631, 951"
countries_perd = c("United Kingdom", "Brazil", "China", "South Korea")
countries_rerd = c("United Kingdom", "Brazil", "United States", "South Korea", "China")

perd_df = filter(df, variablecode == "PERD", 
                 countrycode %in% c("BR", "UK", "US", "KR", "CN"), sectorcode == sec,
                 year %in% c(2008, 2011), !is.na(value))

rerd_df = filter(df, variablecode == "RERD", 
                 countrycode %in% c("BR", "UK", "US", "KR", "CN"),
                 sectorcode == "TOT",
                 year %in% c(2000:2011),
                 !is.na(value))

### International Benchmark
int_rerd = rerd_df
int_rerd = filter(int_rerd, year %in% c(2000:2011))
### uk tseries
uk_ts_rerd = filter(int_rerd, countrycode == "UK")
uk_ts_rerd = uk_ts_rerd$value
### Brazil Series
br_rerd = filter(rerd_df, countrycode == "BR", !is.na(value))
ts_year_rerd = br_rerd$year
ts_rerd = br_rerd$value
### us tseries
us_ts_rerd = filter(int_rerd, countrycode == "US")
us_ts_rerd = us_ts_rerd$value
### kr tseries
kr_ts_rerd = filter(int_rerd, countrycode == "KR")
kr_ts_rerd = kr_ts_rerd$value
### cn tseries
cn_ts_rerd = filter(int_rerd, countrycode == "CN")
cn_ts_rerd = cn_ts_rerd$value
```


Row
-----------------------------------------------------------------------

### International PERD analysis 

```{r}
slices_perd = c(33352, 21706, 391214, 115595)
pct_perd <- round(slices_perd/sum(slices_perd)*100)
countries_pie_perd <- paste(countries_perd, pct_perd) # add percents to labels
countries_pie_perd <- paste(countries_pie_perd,"%",sep="") # ad % to labels
pie_perd = pie(slices_perd,labels = countries_pie_perd, main="International PERD Comparision - 2011") 
```

### Researchers (RERD)

```{r, echo=FALSE, message=FALSE, warning=FALSE}
### config plot
color = c("blue", "red", "black", "orange", "brown")
types = c('l', "b", "l", "o", "b")
plot_reint = plot(ts_year_rerd, ts_rerd, type = 'l', col = "red",
                  main = "International RERD occupations", ylab = "Researchers", xlab = "Years", ylim = c(40000, 1500000), xlim = c(2000, 2011))
lines(ts_year_rerd, uk_ts_rerd, type = 'b', col = "blue")
lines(ts_year_rerd, us_ts_rerd, type = 'l', col = "black")
lines(ts_year_rerd, kr_ts_rerd, type = 'o', col = "orange")
lines(ts_year_rerd, cn_ts_rerd, type = 'b', col = "brown")
legend("topright", countries, col = color, pch = c(1,1,1,1,1), cex = 0.7)
```

Row
-----------------------------------------------------------------------

###  Remarks

```{r, echo=FALSE, message=FALSE, warning=FALSE}
perd_df = perd_df[,-c(1,2,5,6,7,8,9,10)]
perd_y2008 = filter(perd_df, year == 2008)
perd_y2011 = filter(perd_df, year == 2011)
perd_df = data.frame("2008" = perd_y2008$value, "2011" = perd_y2011$value, row.names = countries_perd)
perd_df = as.data.frame(t(perd_df))
perd_df_m = as.matrix(perd_df)
perd_barplot = barplot(perd_df_m , beside=T, legend.text = T, col=c("blue" , "red"), ylim=c(0,400000), xlab = "Countries", 
                     ylab = "Full Time Equivalent",
                     main = "R&D Personnel - International Comparasion")
```


### Researchers analysis

```{r, echo=FALSE, message=FALSE, warning=FALSE}
slices_rerd = c(89043, 67427, 853000, 223513, 818811)
pct_rerd <- round(slices_rerd/sum(slices_rerd)*100)
countries_pie_rerd <- paste(countries_rerd, pct_rerd) # add percents to labels
countries_pie_rerd <- paste(countries_pie_rerd,"%",sep="") # ad % to labels
pie_rerd = pie(slices_rerd,labels = countries_pie_rerd, main="International RERD Comparision - 2011") 
```

Employment (EMP)
=======================================================================

```{r, message=FALSE, warning=FALSE, include=FALSE}
sec = "A'=B'+C"
countries = c("United Kingdom", "Brazil", "United States", "South Korea", "China")
ts_year_emp = c(2000:2014)

### Filter data
emp_df = filter(df, variablecode == "EMP", 
                countrycode %in% c("BR", "UK", "US", "KR", "CN"), 
                sectorcode == sec, year %in% c(2000:2014))

emp_df = emp_df[,-c(1,2,5,6,7,8,9,10)]

### International Benchmark
int_emp = emp_df
### Brazil tseries
br_ts_emp = filter(int_emp, countrycode == "BR")
br_ts_emp = br_ts_emp$value
### uk tseries
uk_ts_emp = filter(int_emp, countrycode == "UK")
uk_ts_emp = uk_ts_emp$value
### us tseries
us_ts_emp = filter(int_emp, countrycode == "US")
us_ts_emp = us_ts_emp$value
### kr tseries
kr_ts_emp = filter(int_emp, countrycode == "KR")
kr_ts_emp = kr_ts_emp$value
### cn tseries
cn_ts_emp = filter(int_emp, countrycode == "CN")
cn_ts_emp = cn_ts_emp$value


### config plot
color = c("blue", "red", "black", "orange", "brown")
types = c('l', "b", "l", "o", "b")

ts_year_lab = c(2000:2014)
unit_lab = "Thousands of current euros PPS per person"


### Filter data
lab_df = filter(df, variablecode == "PRODEMP", 
                countrycode %in% c("BR", "UK", "US", "KR", "CN"), 
                sectorcode == sec, year %in% c(2000:2014), unit == unit_lab)

lab_df = lab_df[,-c(1,2,5,6,7,8,9,10)]

### International Benchmark
int_lab = lab_df
### Brazil tseries
br_ts_lab = filter(int_lab, countrycode == "BR")
br_ts_lab = br_ts_lab$value
### uk tseries
uk_ts_lab = filter(int_lab, countrycode == "UK")
uk_ts_lab = uk_ts_lab$value
### us tseries
us_ts_lab = filter(int_lab, countrycode == "US")
us_ts_lab = us_ts_lab$value
### kr tseries
kr_ts_lab = filter(int_lab, countrycode == "KR")
kr_ts_lab = kr_ts_lab$value
### cn tseries
cn_ts_lab = filter(int_lab, countrycode == "CN")
cn_ts_lab = cn_ts_lab$value
```


Row
-----------------------------------------------------------------------

### International Employment analysis 

```{r, echo=FALSE, message=FALSE, warning=FALSE}
plot_empint = plot(ts_year_emp, br_ts_emp, type = 'b', col = "red",
                   main = "International emp", cex.axis=0.8, ylab = "100 persons", xlab = "Years", ylim = c(500, 15000), xlim=c(2000, 2015))
lines(ts_year_emp, uk_ts_emp, type = 'l', col = "blue")
lines(ts_year_emp, us_ts_emp, type = 'l', col = "black")
lines(ts_year_emp, kr_ts_emp, type = 'o', col = "orange")
lines(ts_year_emp, cn_ts_emp, type = 'b', col = "brown")
legend("topleft", countries, col = color, pch = c(1,1,1,1,1), cex = .8)
```

### Productivity

```{r, echo=FALSE, message=FALSE, warning=FALSE}
plot_labint = plot(ts_year_lab, br_ts_lab, type = 'b', col = "red",
                   main = "International lab", cex.axis=0.8, ylab = "100 persons", xlab = "Years", ylim = c(10, 200), xlim=c(2000, 2015))
lines(ts_year_lab, uk_ts_lab, type = 'l', col = "blue")
lines(ts_year_lab, us_ts_lab, type = 'l', col = "black")
lines(ts_year_lab, kr_ts_lab, type = 'o', col = "orange")
lines(ts_year_lab, cn_ts_lab, type = 'b', col = "brown")
legend("topleft", countries, col = color, pch = c(1,1,1,1,1), cex = .8)
```

Row
-----------------------------------------------------------------------

###  International Benchmark

```{r, echo=FALSE, message=FALSE, warning=FALSE}
slices_emp = c(1022, 1259, 4138, 1087, 14693)
pct_emp <- round(slices_emp/sum(slices_emp)*100)
countries_pie_emp <- paste(countries, pct_emp) # add percents to labels
countries_pie_emp <- paste(countries_pie_emp,"%",sep="") # ad % to labels
pie_emp = pie(slices_emp,labels = countries_pie_emp, main="International emp - 2014") 
```

### Productivity

```{r}
boxp_lab_int = boxplot(uk_ts_lab, br_ts_lab, us_ts_lab, kr_ts_lab, cn_ts_lab, names = countries, main = "International lab Comparision", ylab = "persons", cex.axis=0.8)
```


NoLI Model 
=======================================================================

Column
-------------------------------------
    
### GERD - MODEL
    
```{r}
model_gerd = ts_gerd * .20
plot_gebr = plot(ts_year, ts_gerd, type = 'l', col = "blue",
                 main = "Brazilian GERD Expenditures", ylab = euro_lab, 
                 xlab = "Years", ylim = c(0, 30000), xlim = c(2000, 2013))
lines(ts_year, model_gerd, type = 'b', col = "red")
legend("topleft", c("LI", "noLI"), col = color, pch = c(1,1,1,1,1))
```
    
### EMPLOYMENT - MODEL

```{r, echo=FALSE, message=FALSE, warning=FALSE}
model_emp = br_ts_emp * .70
plot_empint = plot(ts_year_emp, br_ts_emp, type = 'l', col = "blue",
                   main = "International emp", cex.axis=0.8, ylab = "100 persons", xlab = "Years", ylim = c(0, 1500), xlim=c(2000, 2015))
lines(ts_year_emp, model_emp, type = 'b', col = "red")
legend("topleft", c("LI", "noLI"), col = color, pch = c(1,1,1,1,1))
```

Column
-------------------------------------
    
### GVA - MODEL
    
```{r, echo=FALSE}
model_gva = br_ts_gva * .25
plot_gvaint = plot(ts_year_gva, br_ts_gva, type = 'l', col = "blue",
                   main = "International GVA", cex.axis=0.8, 
                   ylab = euro_lab, xlab = "Years", 
                   xlim=c(1995, 2015), ylim = c(4000, 80000))
lines(ts_year_gva, model_gva, type = 'b', col = "red")
legend("topleft", c("LI", "noLI"), col = color, pch = c(1,1,1,1,1))
```
    
### PRODUCTIVITY - MODEL

```{r, echo=FALSE, message=FALSE, warning=FALSE}
model_lab = br_ts_lab * .70
plot_labint = plot(ts_year_lab, br_ts_lab, type = 'l', col = "blue",
                   main = "International lab", cex.axis=0.8, ylab = "100 persons", xlab = "Years", ylim = c(0, 100), xlim=c(2000, 2015))
lines(ts_year_lab, model_lab, type = 'b', col = "red")
legend("topleft", c("LI", "noLI"), col = color, pch = c(1,1,1,1,1))
```

